### ISSUE TITLE
Error with UUID

### ISSUE THREAD

**Issue by nexttoyou** [materik/homebridge-harmonyhub#3]
Hello,

there seems to be a problem with a non valid UUID at least at my side. I’m running your plugin with homebridge in a Docker container using [oznu/homebridge-syno-spk](https://github.com/oznu/homebridge-syno-spk) on a Synology Disk Station.

Many thanks in advance!

```
[2018-10-29 13:40:51] [HarmonyHub] {Plugin} loadAccessories: Error: UUID '78d7d33a-5cb0-4d6c-0c3a-9daf84d62fbf' is not a valid UUID. Try using the provided 'generateUUID' function to create a valid UUID from any arbitrary string, like a serial number.
    at new PlatformAccessory (/usr/local/lib/node_modules/homebridge/lib/platformAccessory.js:17:34)
    at new Accessory (/homebridge/node_modules/homebridge-harmonyhub/lib/accessory.js:12:13)
    at new HarmonyHubAccessory (/homebridge/node_modules/homebridge-harmonyhub/lib/harmonyhub-accessory.js:17:35)
    at /homebridge/node_modules/homebridge-harmonyhub/lib/plugin.js:51:18
    at arrayMap (/homebridge/node_modules/homebridge-harmonyhub/node_modules/lodash/lodash.js:631:23)
    at Function.map (/homebridge/node_modules/homebridge-harmonyhub/node_modules/lodash/lodash.js:9546:14)
    at /homebridge/node_modules/homebridge-harmonyhub/lib/plugin.js:43:13
    at tryCallOne (/homebridge/node_modules/promise/lib/core.js:37:12)
    at /homebridge/node_modules/promise/lib/core.js:123:15
    at flush (/homebridge/node_modules/asap/raw.js:50:29)
    at _combinedTickCallback (internal/process/next_tick.js:132:7)
    at process._tickCallback (internal/process/next_tick.js:181:9)
```

**Comment by nicoh88** [comment]
Same here with RPi 3 und Homebridge

```
Oct 29 15:34:56 rpi-smarthome homebridge[16026]: [2018-10-29 15:34:56] [Harmony Hub] {HarmonyHub} Found <1> hubs
Oct 29 15:34:56 rpi-smarthome homebridge[16026]: [2018-10-29 15:34:56] [Harmony Hub] {HarmonyHub} <92195dbf-776c-4a42-2a00-d0f3ab0113ea> <Harmony Hub>
Oct 29 15:34:57 rpi-smarthome homebridge[16026]: [2018-10-29 15:34:57] [Harmony Hub] {Plugin} loadAccessories: Error: UUID '92195dbf-776c-4a42-2a00-d0f3ab0113ea' is not a valid UUID. Try using the provided 'generateUUID' function to create a valid UUID from any arbitrary string, like a serial number.
Oct 29 15:34:57 rpi-smarthome homebridge[16026]:     at new PlatformAccessory (/usr/lib/node_modules/homebridge/lib/platformAccessory.js:17:34)
Oct 29 15:34:57 rpi-smarthome homebridge[16026]:     at new Accessory (/usr/lib/node_modules/homebridge-harmonyhub/lib/accessory.js:12:13)
Oct 29 15:34:57 rpi-smarthome homebridge[16026]:     at new HarmonyHubAccessory (/usr/lib/node_modules/homebridge-harmonyhub/lib/harmonyhub-accessory.js:17:35)
Oct 29 15:34:57 rpi-smarthome homebridge[16026]:     at /usr/lib/node_modules/homebridge-harmonyhub/lib/plugin.js:51:18
Oct 29 15:34:57 rpi-smarthome homebridge[16026]:     at arrayMap (/usr/lib/node_modules/homebridge-harmonyhub/node_modules/lodash/lodash.js:631:23)
Oct 29 15:34:57 rpi-smarthome homebridge[16026]:     at Function.map (/usr/lib/node_modules/homebridge-harmonyhub/node_modules/lodash/lodash.js:9546:14)
Oct 29 15:34:57 rpi-smarthome homebridge[16026]:     at /usr/lib/node_modules/homebridge-harmonyhub/lib/plugin.js:43:13
Oct 29 15:34:57 rpi-smarthome homebridge[16026]:     at tryCallOne (/usr/lib/node_modules/homebridge-harmonyhub/node_modules/promise/lib/core.js:37:12)
Oct 29 15:34:57 rpi-smarthome homebridge[16026]:     at /usr/lib/node_modules/homebridge-harmonyhub/node_modules/promise/lib/core.js:123:15
Oct 29 15:34:57 rpi-smarthome homebridge[16026]:     at flush (/usr/lib/node_modules/homebridge-harmonyhub/node_modules/asap/raw.js:50:29)
```

**Comment by materik** [comment]
@nexttoyou @nicoh88 could you try this potential fix by installing
```
npm install -g materik/homebridge-harmonyhub#bugfix/3
```

**Comment by nicoh88** [comment]
Yes! It works!

```
[2018-10-29 19:34:29] [HarmonyHub] {Accessory} fromAccessory
[2018-10-29 19:34:29] [HarmonyHub] {Accessory} <0f7cb4f2-eeef-4fb9-aaf0-3ed7ae5753a0> <Harmony Hub>
[2018-10-29 19:34:29] [HarmonyHub] {HarmonyHubAccessory} fromAccessory
[2018-10-29 19:34:29] [HarmonyHub] {HarmonyHubAccessory} <0f7cb4f2-eeef-4fb9-aaf0-3ed7ae5753a0> <Harmony Hub>
[2018-10-29 19:34:29] [HarmonyHub] {Plugin} configureAccessory: <Harmony Hub>
[2018-10-29 19:34:29] [HarmonyHub] {Plugin} didFinishLaunching
[2018-10-29 19:34:29] [HarmonyHub] {Plugin} loadAccessories
[2018-10-29 19:34:29] [HarmonyHub] {HarmonyHub} finding hubs
[2018-10-29 19:34:31] [HarmonyHub] {HarmonyHub} Found <1> hubs
[2018-10-29 19:34:31] [HarmonyHub] {HarmonyHub} <0777bfd0-458c-410a-a1ec-b6b1c6e5b3c8> <Harmony Hub>
[2018-10-29 19:34:31] [HarmonyHub] {Accessory} <0777bfd0-458c-410a-a1ec-b6b1c6e5b3c8> <Harmony Hub>
[2018-10-29 19:34:31] [HarmonyHub] {HarmonyHubAccessory} <0777bfd0-458c-410a-a1ec-b6b1c6e5b3c8> <Harmony Hub>
[2018-10-29 19:34:31] [HarmonyHub] {HarmonyHubAccessory} found <0> services
[2018-10-29 19:34:31] [HarmonyHub] {Plugin} registering <1> platform accessories
[2018-10-29 19:34:31] [HarmonyHub] {HarmonyHub} create new client for <Harmony Hub>
[2018-10-29 19:34:31] [HarmonyHub] {HarmonyHub} get activities
[2018-10-29 19:34:32] [HarmonyHub] {Activity} <25552952> <Media Center>
[2018-10-29 19:34:32] [HarmonyHub] {Activity} <28828367> <PlayStation 4>
[2018-10-29 19:34:32] [HarmonyHub] {HarmonyHub} Found <2> activities: <Media Center, PlayStation 4>
[2018-10-29 19:34:32] [HarmonyHub] {HarmonyHubAccessory} adding <2> activities
[2018-10-29 19:34:32] [HarmonyHub] {HarmonyHubAccessory} addActivity <Media Center>
[2018-10-29 19:34:33] [HarmonyHub] {ActivityService} <25552952> <Media Center>
[2018-10-29 19:34:33] [HarmonyHub] {Service} <25552952> <Media Center>
[2018-10-29 19:34:33] [HarmonyHub] {HarmonyHubAccessory} addActivity <PlayStation 4>
[2018-10-29 19:34:33] [HarmonyHub] {ActivityService} <28828367> <PlayStation 4>
[2018-10-29 19:34:33] [HarmonyHub] {Service} <28828367> <PlayStation 4>
[2018-10-29 19:34:33] [HarmonyHub] {HarmonyHubAccessory} update states for <2> services
[2018-10-29 19:34:33] [HarmonyHub] {HarmonyHubAccessory} handle state changes for <2> services
[2018-10-29 19:34:33] [HarmonyHub] {Service} set <Media Center> <off>
[2018-10-29 19:34:33] [HarmonyHub] {Service} set <PlayStation 4> <off>
```

Thanks Bro! 👍

**Comment by materik** [comment]
Awesome 👏

**Comment by materik** [comment]
I have released this fix as version 0.4.0.
```
npm install -g materik/homebridge-harmonyhub#0.4.0
```

**Comment by nicoh88** [comment]
Perfect, thanks. 😋 

You could / should edit the `package.json`, version 0.2.0 to 0.4.0. 😅

**Comment by materik** [comment]
Ah. Forgot that. Thanks! 😉

**Comment by DJay-X** [comment]
@materik Just removed the "old" HarmonyHub Plugin and switched to yours @0.4.0. 
Works gerat. RPi 3B+ Homebridge  0.4.45, Node 11.1.0
Thanks a lot for your work and sharing, and if necessary for your ongoing development. 👍🏻

**Comment by perlbo** [comment]
does this version work now with firmware 206 ?
